"""
Script de UMA VEZ para gerar um catalogo grande em data/conhecimento.json.
Roda com: python scripts/gerar_enciclopedia.py
Nao faz parte do runtime da JARVIS - e so uma ferramenta de montagem do catalogo.
"""
import json
from pathlib import Path

CAMINHO = Path(__file__).resolve().parent.parent / "data" / "conhecimento.json"

# Entradas ja existentes (identidade da JARVIS, matematica basica, historia,
# geopolitica) sao preservadas; aqui so ADICIONAMOS uma leva grande de novas.
NOVAS = []

def add(categoria, perguntas, resposta):
    NOVAS.append({"categoria": categoria, "perguntas": perguntas, "resposta": resposta})

# ---------------------------------------------------------------- MATEMATICA
add("matematica", ["o que e uma equacao de primeiro grau"], "Equação de primeiro grau é uma equação em que a incógnita aparece com expoente 1, na forma a x mais b igual a zero.")
add("matematica", ["o que e uma funcao"], "Função é uma relação matemática em que cada valor de entrada corresponde a exatamente um valor de saída.")
add("matematica", ["o que e um numero racional"], "Número racional é todo número que pode ser escrito como fração de dois inteiros, como 1/2 ou 3/4.")
add("matematica", ["o que e um numero irracional"], "Número irracional é aquele que não pode ser escrito como fração exata, como pi ou a raiz de 2.")
add("matematica", ["o que e area de um circulo", "formula da area do circulo"], "A área do círculo é pi vezes o raio ao quadrado.")
add("matematica", ["o que e o perimetro de um circulo", "formula do perimetro do circulo"], "O perímetro de um círculo é 2 vezes pi vezes o raio.")
add("matematica", ["formula da area de um triangulo"], "A área de um triângulo é base vezes altura, dividido por 2.")
add("matematica", ["formula da area de um quadrado"], "A área de um quadrado é o lado ao quadrado.")
add("matematica", ["formula da area de um retangulo"], "A área de um retângulo é base vezes altura.")
add("matematica", ["o que e porcentagem"], "Porcentagem é uma razão em que o denominador é 100, representando uma parte de um total.")
add("matematica", ["o que e media aritmetica"], "Média aritmética é a soma de todos os valores dividida pela quantidade de valores.")
add("matematica", ["o que e um numero fatorial", "o que e fatorial"], "Fatorial de um número é o produto dele por todos os inteiros positivos menores que ele, representado pelo símbolo de exclamação.")
add("matematica", ["quanto e a raiz quadrada de cem"], "A raiz quadrada de 100 é 10.")
add("matematica", ["quanto e a raiz quadrada de dois"], "A raiz quadrada de 2 é aproximadamente 1,41.")
add("matematica", ["o que e logaritmo"], "Logaritmo é a operação que indica o expoente ao qual uma base deve ser elevada para se obter determinado número.")
add("matematica", ["o que e um angulo reto"], "Ângulo reto é aquele que mede exatamente 90 graus.")
add("matematica", ["o que e um angulo obtuso"], "Ângulo obtuso é aquele que mede mais de 90 e menos de 180 graus.")
add("matematica", ["o que e um angulo agudo"], "Ângulo agudo é aquele que mede menos de 90 graus.")
add("matematica", ["quantos lados tem um hexagono"], "Um hexágono tem 6 lados.")
add("matematica", ["quantos lados tem um pentagono"], "Um pentágono tem 5 lados.")
add("matematica", ["o que e o numero de euler"], "O número de Euler, representado por e, vale aproximadamente 2,718 e aparece em crescimento exponencial e logaritmos naturais.")

# --------------------------------------------------------------- FISICA/QUIMICA
add("ciencias", ["qual e a velocidade da luz"], "A velocidade da luz no vácuo é de aproximadamente 300 mil quilômetros por segundo.")
add("ciencias", ["quem descobriu a gravidade", "lei da gravitacao universal"], "Isaac Newton formulou a lei da gravitação universal no século 17, descrevendo como os corpos se atraem.")
add("ciencias", ["quem foi albert einstein"], "Albert Einstein foi um físico alemão que criou a teoria da relatividade e ganhou o Nobel de Física em 1921.")
add("ciencias", ["o que e a teoria da relatividade"], "A teoria da relatividade, de Einstein, descreve como espaço, tempo e gravidade se relacionam, incluindo a famosa equação E igual a m c ao quadrado.")
add("ciencias", ["quantos elementos tem a tabela periodica"], "A tabela periódica tem 118 elementos químicos confirmados.")
add("ciencias", ["qual e o simbolo do oxigenio"], "O símbolo químico do oxigênio é O.")
add("ciencias", ["qual e o simbolo da agua", "formula quimica da agua"], "A fórmula química da água é H2O: dois átomos de hidrogênio e um de oxigênio.")
add("ciencias", ["o que e dna"], "DNA é a molécula que guarda as informações genéticas dos seres vivos.")
add("ciencias", ["quem criou a teoria da evolucao"], "Charles Darwin propôs a teoria da evolução das espécies por seleção natural, publicada em 1859.")
add("ciencias", ["quantos ossos tem o corpo humano"], "O corpo humano adulto tem 206 ossos.")

# --------------------------------------------------------------- ASTRONOMIA
add("astronomia", ["quantos planetas tem o sistema solar"], "O sistema solar tem 8 planetas: Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno.")
add("astronomia", ["qual e o maior planeta do sistema solar"], "Júpiter é o maior planeta do sistema solar.")
add("astronomia", ["qual e o menor planeta do sistema solar"], "Mercúrio é o menor planeta do sistema solar.")
add("astronomia", ["qual e o planeta mais proximo do sol"], "Mercúrio é o planeta mais próximo do Sol.")
add("astronomia", ["quanto tempo a terra leva para dar uma volta no sol"], "A Terra leva aproximadamente 365 dias e um quarto para dar uma volta completa ao redor do Sol.")
add("astronomia", ["o que e um buraco negro"], "Buraco negro é uma região do espaço com gravidade tão forte que nem a luz consegue escapar dela.")
add("astronomia", ["quem foi o primeiro homem a ir a lua"], "Neil Armstrong foi o primeiro homem a pisar na Lua, em 20 de julho de 1969, na missão Apollo 11.")
add("astronomia", ["o que e a via lactea"], "Via Láctea é o nome da galáxia onde está o nosso sistema solar.")

# --------------------------------------------------------------- GEOGRAFIA
add("geografia", ["quantos continentes existem"], "Existem 6 continentes: África, América, Antártida, Ásia, Europa e Oceania.")
add("geografia", ["qual e o maior pais do mundo"], "A Rússia é o maior país do mundo em área territorial.")
add("geografia", ["qual e o maior pais da america do sul"], "O Brasil é o maior país da América do Sul.")
add("geografia", ["qual e o maior oceano do mundo"], "O Oceano Pacífico é o maior e mais profundo oceano do mundo.")
add("geografia", ["qual e o maior rio do mundo"], "O Rio Amazonas é considerado o maior rio do mundo em volume de água.")
add("geografia", ["qual e a maior floresta do mundo"], "A Floresta Amazônica é a maior floresta tropical do mundo.")
add("geografia", ["qual e o deserto mais quente do mundo"], "O Deserto do Saara, na África, é o maior deserto quente do mundo.")
add("geografia", ["qual e a montanha mais alta do mundo"], "O Monte Everest, no Himalaia, é a montanha mais alta do mundo, com cerca de 8.849 metros.")
add("geografia", ["qual e a capital do brasil"], "A capital do Brasil é Brasília.")
add("geografia", ["qual e a capital da franca"], "A capital da França é Paris.")
add("geografia", ["qual e a capital dos estados unidos"], "A capital dos Estados Unidos é Washington.")
add("geografia", ["qual e a capital da inglaterra", "qual e a capital do reino unido"], "A capital do Reino Unido é Londres.")
add("geografia", ["qual e a capital da alemanha"], "A capital da Alemanha é Berlim.")
add("geografia", ["qual e a capital da italia"], "A capital da Itália é Roma.")
add("geografia", ["qual e a capital da china"], "A capital da China é Pequim.")
add("geografia", ["qual e a capital do japao"], "A capital do Japão é Tóquio.")
add("geografia", ["qual e a capital da russia"], "A capital da Rússia é Moscou.")
add("geografia", ["qual e a capital da argentina"], "A capital da Argentina é Buenos Aires.")
add("geografia", ["quantos estados tem o brasil"], "O Brasil tem 26 estados e mais o Distrito Federal, totalizando 27 unidades federativas.")

# --------------------------------------------------------------- HISTORIA BRASIL (extra)
add("historia_brasil", ["quem foi dom pedro segundo"], "Dom Pedro Segundo foi o segundo e último imperador do Brasil, governando de 1840 até a Proclamação da República em 1889.")
add("historia_brasil", ["quem foi tiradentes"], "Tiradentes foi o principal líder da Inconfidência Mineira, movimento contra o domínio português, e foi executado em 1792.")
add("historia_brasil", ["o que foi a inconfidencia mineira"], "A Inconfidência Mineira foi um movimento separatista de 1789 em Minas Gerais contra o domínio de Portugal.")
add("historia_brasil", ["quem foi o primeiro presidente do brasil"], "Deodoro da Fonseca foi o primeiro presidente do Brasil, em 1889, após a Proclamação da República.")
add("historia_brasil", ["quem foi juscelino kubitschek"], "Juscelino Kubitschek foi presidente do Brasil de 1956 a 1961 e é conhecido por construir Brasília.")
add("historia_brasil", ["quando brasilia foi inaugurada"], "Brasília foi inaugurada como capital do Brasil em 21 de abril de 1960.")
add("historia_brasil", ["quem foi o primeiro presidente eleito depois da ditadura"], "Fernando Collor foi o primeiro presidente eleito por voto direto após a ditadura militar, tomando posse em 1990.")
add("historia_brasil", ["o que foi o plano real"], "O Plano Real foi o programa econômico de 1994 que criou a moeda Real e controlou a hiperinflação no Brasil.")
add("historia_brasil", ["quem foi jose sarney"], "José Sarney foi o primeiro presidente civil do Brasil após a ditadura militar, governando de 1985 a 1990.")

# --------------------------------------------------------------- HISTORIA MUNDIAL (extra)
add("historia_mundial", ["o que foi o iluminismo"], "Iluminismo foi um movimento filosófico do século 18 na Europa que defendia a razão, a ciência e os direitos individuais.")
add("historia_mundial", ["o que foi a revolucao industrial"], "A Revolução Industrial começou na Inglaterra no século 18 e transformou a produção artesanal em produção mecanizada em fábricas.")
add("historia_mundial", ["o que foi a guerra fria"], "A Guerra Fria foi a disputa política e ideológica entre Estados Unidos e União Soviética, de 1947 a 1991, sem confronto militar direto entre as duas potências.")
add("historia_mundial", ["quem foi hitler", "quem foi adolf hitler"], "Adolf Hitler foi o ditador da Alemanha nazista de 1933 a 1945, responsável pelo Holocausto e por iniciar a Segunda Guerra Mundial na Europa.")
add("historia_mundial", ["o que foi o holocausto"], "O Holocausto foi o extermínio sistemático de cerca de 6 milhões de judeus e outras minorias pela Alemanha nazista durante a Segunda Guerra Mundial.")
add("historia_mundial", ["quem foi napoleao bonaparte"], "Napoleão Bonaparte foi um general e imperador francês que dominou boa parte da Europa no início do século 19.")
add("historia_mundial", ["o que foi o egito antigo conhecido por"], "O Egito Antigo é conhecido pelas pirâmides, pelos faraós e por ser uma das primeiras grandes civilizações da história, às margens do Rio Nilo.")
add("historia_mundial", ["o que foi o imperio romano"], "O Império Romano foi uma das maiores civilizações da história antiga, controlando boa parte da Europa, norte da África e Oriente Médio.")
add("historia_mundial", ["quando o imperio romano caiu"], "O Império Romano do Ocidente caiu em 476 depois de Cristo.")
add("historia_mundial", ["o que foi a guerra do vietna"], "A Guerra do Vietnã foi um conflito entre 1955 e 1975 que envolveu o Vietnã do Norte, apoiado pela União Soviética e China, contra o Vietnã do Sul, apoiado pelos Estados Unidos.")

# --------------------------------------------------------------- GEOPOLITICA (extra)
add("geopolitica", ["o que e a otan e quem faz parte", "quais paises fazem parte da otan"], "A OTAN é formada principalmente por países da Europa e América do Norte, incluindo Estados Unidos, Reino Unido, Alemanha, França e Canadá.")
add("geopolitica", ["o que e o g7"], "O G7 é um grupo formado pelas sete maiores economias desenvolvidas do mundo: Estados Unidos, Japão, Alemanha, Reino Unido, França, Itália e Canadá.")
add("geopolitica", ["o que e o g20"], "O G20 é um grupo formado pelas 19 maiores economias do mundo mais a União Europeia, para discutir política econômica global.")
add("geopolitica", ["o que e uma democracia"], "Democracia é um sistema de governo em que o poder vem do povo, geralmente exercido por meio do voto e de representantes eleitos.")
add("geopolitica", ["o que e uma monarquia"], "Monarquia é um sistema de governo em que o poder é exercido por um rei ou rainha, podendo ser absoluta ou constitucional.")
add("geopolitica", ["o que e um pais em desenvolvimento"], "País em desenvolvimento é aquele que ainda está construindo sua estrutura econômica e social, geralmente com renda per capita menor que a de países desenvolvidos.")
add("geopolitica", ["quantos paises tem o mundo"], "Existem cerca de 195 países reconhecidos internacionalmente no mundo.")

# ---------------------------------------------------------------- ROBOTICA
add("robotica", ["o que e robotica"], "Robótica é a área que projeta, constrói e programa robôs, unindo mecânica, eletrônica e software.")
add("robotica", ["o que e um atuador"], "Atuador é o componente de um robô que transforma energia (elétrica, hidráulica ou pneumática) em movimento, como motores e servos.")
add("robotica", ["o que e um sensor em robotica"], "Sensor é o componente que permite ao robô perceber o ambiente, medindo grandezas como distância, temperatura, luz ou posição.")
add("robotica", ["o que e um servo motor", "para que serve um servo motor"], "Servo motor é um motor que permite controlar precisamente a posição angular do eixo, muito usado em robótica e automação.")
add("robotica", ["o que e um braco robotico"], "Braço robótico é um manipulador mecânico com juntas articuladas, usado para replicar movimentos humanos em tarefas de montagem, solda ou manuseio de peças.")
add("robotica", ["o que e automacao industrial"], "Automação industrial é o uso de máquinas, robôs e sistemas de controle para executar tarefas de produção sem intervenção humana constante.")
add("robotica", ["quantos graus de liberdade tem um robo"], "Graus de liberdade é o número de movimentos independentes que um robô pode fazer; um braço robótico industrial típico tem de 4 a 6 graus de liberdade.")
add("robotica", ["o que e um cobot", "o que e robo colaborativo"], "Cobot, ou robô colaborativo, é um robô projetado para trabalhar em conjunto com pessoas no mesmo espaço, com sensores de segurança para evitar acidentes.")

# ---------------------------------------------------------------- IA
add("ia", ["o que e inteligencia artificial"], "Inteligência artificial é a área da computação que cria sistemas capazes de realizar tarefas que normalmente exigiriam raciocínio humano, como reconhecer padrões e tomar decisões.")
add("ia", ["o que e machine learning", "o que e aprendizado de maquina"], "Machine learning é um ramo da inteligência artificial em que o sistema aprende padrões a partir de dados, em vez de seguir regras programadas manualmente.")
add("ia", ["o que e uma rede neural"], "Rede neural é um modelo de inteligência artificial inspirado no funcionamento do cérebro, formado por camadas de nós conectados que processam informação.")
add("ia", ["o que e deep learning", "o que e aprendizado profundo"], "Deep learning é uma técnica de machine learning que usa redes neurais com muitas camadas para aprender padrões complexos, como em reconhecimento de imagem e voz.")
add("ia", ["o que e visao computacional"], "Visão computacional é a área da inteligência artificial que permite a máquinas interpretar imagens e vídeos, usada por exemplo para inspecionar peças automaticamente.")
add("ia", ["o que e um llm", "o que e um modelo de linguagem"], "LLM, ou modelo de linguagem grande, é um tipo de inteligência artificial treinado com muito texto para entender e gerar linguagem natural, como o modelo usado pela própria JARVIS.")
add("ia", ["o que e um chatbot"], "Chatbot é um programa que conversa com pessoas por texto ou voz, respondendo perguntas ou executando tarefas automaticamente.")
add("ia", ["o que e manutencao preditiva"], "Manutenção preditiva é o uso de dados e inteligência artificial para prever falhas em máquinas antes que elas aconteçam, evitando paradas inesperadas.")

# ---------------------------------------------------------------- MANUFATURA ADITIVA / IMPRESSAO 3D
add("manufatura_aditiva", ["o que e manufatura aditiva"], "Manufatura aditiva é o nome técnico da impressão 3D: construir uma peça adicionando material camada por camada, ao contrário da usinagem que remove material.")
add("manufatura_aditiva", ["o que e fdm", "o que e impressao fdm"], "FDM, ou modelagem por fusão e depósito, é a tecnologia de impressão 3D que derrete um filamento de plástico e o deposita camada por camada.")
add("manufatura_aditiva", ["o que e sla", "o que e impressao sla"], "SLA, ou estereolitografia, é uma tecnologia de impressão 3D que usa um laser para curar resina líquida camada por camada, gerando peças de alta precisão.")
add("manufatura_aditiva", ["o que e sls", "o que e impressao sls"], "SLS, ou sinterização seletiva a laser, é uma tecnologia de impressão 3D que usa laser para fundir pó de material (plástico ou metal) camada por camada.")
add("manufatura_aditiva", ["o que e um slicer", "para que serve um slicer"], "Slicer é o software que converte um modelo 3D em camadas e gera o código G, com as instruções que a impressora 3D vai seguir para imprimir.")
add("manufatura_aditiva", ["o que e codigo g", "o que e g-code"], "Código G, ou G-code, é a linguagem de instruções que controla os movimentos e a extrusão de uma impressora 3D ou máquina CNC.")
add("manufatura_aditiva", ["o que e infill", "o que e preenchimento na impressao 3d"], "Infill é o preenchimento interno de uma peça impressa em 3D; controla a densidade e resistência da peça sem gastar material extra em uma peça totalmente sólida.")
add("manufatura_aditiva", ["o que e suporte na impressao 3d", "para que serve suporte na impressao 3d"], "Suporte é uma estrutura auxiliar impressa para sustentar partes da peça que ficariam suspensas no ar, sendo removida depois da impressão.")
add("manufatura_aditiva", ["quais materiais mais usados na impressao 3d"], "Os materiais mais comuns em impressão 3D FDM são PLA, ABS, PETG e nylon, cada um com diferentes níveis de resistência, flexibilidade e temperatura de uso.")
add("manufatura_aditiva", ["o que e pla"], "PLA é um plástico biodegradável derivado de milho ou cana-de-açúcar, muito usado em impressão 3D por ser fácil de imprimir e ter boa qualidade visual.")
add("manufatura_aditiva", ["o que e abs"], "ABS é um plástico resistente e mais tolerante ao calor que o PLA, usado em impressão 3D para peças que precisam de mais durabilidade mecânica.")
add("manufatura_aditiva", ["o que e petg"], "PETG é um plástico que combina a facilidade de impressão do PLA com mais resistência e flexibilidade, sendo resistente à umidade.")
add("manufatura_aditiva", ["o que e um extrusor de impressora 3d"], "Extrusor é a parte da impressora 3D que puxa o filamento, o derrete e o empurra através do bico para formar cada camada da peça.")
add("manufatura_aditiva", ["o que e a mesa de impressao", "o que e a build plate"], "Mesa de impressão, ou build plate, é a superfície onde a peça é construída camada por camada; sua nivelação e aderência são essenciais para uma boa impressão.")
add("manufatura_aditiva", ["o que e warping na impressao 3d"], "Warping é o empenamento da peça durante a impressão 3D, geralmente causado por resfriamento desigual do material, comum em ABS.")
add("manufatura_aditiva", ["o que e resina de impressao 3d"], "Resina é o material líquido fotossensível usado em impressoras 3D de resina (SLA/DLP), que endurece quando exposto à luz ultravioleta.")

# ---------------------------------------------------------------- AERONAVES
add("aeronave", ["o que faz um aviao voar", "como um aviao voa"], "Um avião voa graças à sustentação gerada pelo formato das asas, que faz o ar passar mais rápido por cima e criar uma diferença de pressão que empurra a aeronave para cima.")
add("aeronave", ["o que e sustentacao na aviacao"], "Sustentação é a força aerodinâmica que empurra a aeronave para cima, gerada principalmente pelo formato das asas em movimento no ar.")
add("aeronave", ["o que e arrasto na aviacao"], "Arrasto é a força que se opõe ao movimento de uma aeronave no ar, causada pelo atrito e pela resistência do ar.")
add("aeronave", ["quem inventou o aviao"], "Os irmãos Wright são reconhecidos por realizar o primeiro voo motorizado controlado, em 1903, nos Estados Unidos; no Brasil, Santos Dumont é celebrado pelo voo do 14-Bis em 1906.")
add("aeronave", ["quem foi santos dumont"], "Santos Dumont foi um inventor brasileiro considerado o pai da aviação por muitos, famoso pelo voo do 14-Bis em Paris, em 1906.")
add("aeronave", ["o que e um drone"], "Drone é uma aeronave não tripulada, controlada remotamente ou de forma autônoma, usada para fotografia, inspeção industrial, entrega e outras aplicações.")
add("aeronave", ["para que serve impressao 3d na aviacao", "impressao 3d e aeronaves"], "A impressão 3D é usada na aviação para fabricar peças leves e complexas, como suportes, dutos e componentes de interior, reduzindo peso e tempo de produção.")
add("aeronave", ["o que e um turbofan", "o que e um motor a jato"], "Turbofan é o tipo de motor a jato mais usado em aviões comerciais, que combina um grande ventilador frontal com uma turbina a gás para gerar empuxo.")

# ---------------------------------------------------------------- PECAS ANTIGAS / CUSTOM DE CARROS
add("carros_antigos", ["o que e uma peca automotiva descontinuada", "o que e uma peca fora de linha"], "Peça automotiva descontinuada, ou fora de linha, é aquela que o fabricante original parou de produzir, geralmente de carros antigos, sendo difícil de encontrar no mercado.")
add("carros_antigos", ["como conseguir pecas de carros antigos", "onde achar peca de carro antigo"], "Peças de carros antigos costumam ser encontradas em desmanches, encontros de colecionadores, ou recriadas por engenharia reversa e impressão 3D quando não existem mais no mercado.")
add("carros_antigos", ["o que e engenharia reversa de pecas"], "Engenharia reversa de peças é o processo de escanear ou medir uma peça original para recriar seu modelo digital, permitindo fabricá-la de novo por impressão 3D ou usinagem.")
add("carros_antigos", ["para que serve impressao 3d para carros antigos", "impressao 3d em restauracao de carros"], "A impressão 3D permite recriar peças de carros antigos que não são mais fabricadas, como acabamentos, suportes e maçanetas, a partir de um modelo digitalizado ou desenhado.")
add("carros_antigos", ["o que e um carro custom", "o que e customizacao automotiva"], "Carro custom é um veículo modificado com peças, acabamentos ou mecânica personalizados, muitas vezes únicos, fora do padrão de fábrica.")
add("carros_antigos", ["o que e escaneamento 3d de peca", "o que e scanner 3d"], "Escaneamento 3D é a técnica de capturar a forma exata de um objeto físico com um scanner a laser ou luz estruturada, gerando um modelo digital pronto para reproduzir ou modificar.")
add("carros_antigos", ["o que e prototipagem rapida"], "Prototipagem rápida é o uso de tecnologias como a impressão 3D para criar rapidamente um modelo físico de uma peça ou produto, antes da fabricação final.")

# =============================================================================
# LOTE 3 - temas aleatorios/variados (animais, corpo humano, alimentacao,
# esportes, musica, arte, cinema/literatura, tecnologia, economia, natureza,
# saude, informatica, curiosidades gerais).
# =============================================================================

# ---------------------------------------------------------------- ANIMAIS
add("animais", ["qual e o maior animal do mundo"], "A baleia-azul é o maior animal do mundo, podendo chegar a 30 metros de comprimento.")
add("animais", ["qual e o animal terrestre mais rapido"], "A chita é o animal terrestre mais rápido, podendo atingir mais de 100 quilômetros por hora.")
add("animais", ["qual e o maior animal terrestre"], "O elefante africano é o maior animal terrestre da atualidade.")
add("animais", ["quanto tempo vive uma tartaruga"], "Algumas espécies de tartaruga podem viver mais de 100 anos.")
add("animais", ["o que os pandas comem"], "Pandas gigantes se alimentam principalmente de bambu, quase 12 horas por dia.")
add("animais", ["qual e o unico mamifero que voa"], "O morcego é o único mamífero capaz de voar de verdade, e não apenas planar.")
add("animais", ["quantos coracoes tem um polvo"], "O polvo tem 3 corações: dois bombeiam sangue para as brânquias e um para o resto do corpo.")
add("animais", ["qual animal tem a maior memoria"], "Elefantes são famosos por sua excelente memória, conseguindo lembrar de rotas e outros indivíduos por décadas.")
add("animais", ["quantos anos vive um cachorro"], "A maioria dos cães vive entre 10 e 13 anos, dependendo da raça e do porte.")
add("animais", ["qual e a ave mais rapida do mundo"], "O falcão-peregrino é a ave mais rápida do mundo, podendo passar de 300 quilômetros por hora em mergulho.")
add("animais", ["quantos ossos tem uma girafa no pescoco"], "A girafa tem 7 vértebras no pescoço, o mesmo número que os humanos, só que bem mais longas.")
add("animais", ["qual e o animal mais venenoso do mundo"], "A água-viva-caixa é considerada um dos animais mais venenosos do mundo.")
add("animais", ["qual e o maior peixe do mundo"], "O tubarão-baleia é o maior peixe do mundo, podendo passar de 12 metros de comprimento.")
add("animais", ["as abelhas sao importantes por que", "por que as abelhas sao importantes"], "As abelhas são essenciais porque polinizam grande parte das plantas que produzem os alimentos que consumimos.")
add("animais", ["quanto tempo uma formiga vive"], "Formigas operárias vivem em média algumas semanas a poucos meses, mas rainhas podem viver muitos anos.")
add("animais", ["qual e o animal mais forte do mundo em relacao ao peso"], "O besouro-rola-bosta é considerado um dos animais mais fortes proporcionalmente ao próprio peso.")
add("animais", ["o que e um animal onivoro"], "Animal onívoro é aquele que se alimenta tanto de plantas quanto de outros animais.")
add("animais", ["o que e um animal herbivoro"], "Animal herbívoro é aquele que se alimenta exclusivamente de plantas.")
add("animais", ["o que e um animal carnivoro"], "Animal carnívoro é aquele que se alimenta principalmente de carne de outros animais.")
add("animais", ["qual e o animal simbolo do brasil"], "A arara-azul e o tucano são frequentemente associados como símbolos da fauna brasileira.")

# ---------------------------------------------------------------- CORPO HUMANO / SAUDE
add("corpo_humano", ["quantos litros de sangue tem uma pessoa"], "Um adulto tem em média de 4,5 a 5,5 litros de sangue no corpo.")
add("corpo_humano", ["qual e o maior orgao do corpo humano"], "A pele é o maior órgão do corpo humano.")
add("corpo_humano", ["quantos musculos tem o corpo humano"], "O corpo humano tem mais de 600 músculos.")
add("corpo_humano", ["quantas vezes o coracao bate por minuto"], "O coração humano bate em média entre 60 e 100 vezes por minuto em repouso.")
add("corpo_humano", ["quanto tempo leva para digerir uma refeicao"], "A digestão completa de uma refeição pode levar de 24 a 72 horas, dependendo do alimento.")
add("corpo_humano", ["quantos neuronios tem o cerebro humano"], "O cérebro humano tem cerca de 86 bilhões de neurônios.")
add("corpo_humano", ["qual e a funcao dos rins"], "Os rins filtram o sangue, removendo toxinas e excesso de líquido, que são eliminados na urina.")
add("corpo_humano", ["qual e a funcao do figado"], "O fígado processa nutrientes, filtra toxinas do sangue e produz a bile, que ajuda na digestão de gorduras.")
add("corpo_humano", ["quanto tempo uma pessoa pode ficar sem dormir"], "Ficar sem dormir por longos períodos é perigoso; recordes relatados chegam a cerca de 11 dias, mas isso causa danos sérios à saúde.")
add("corpo_humano", ["quantas horas de sono um adulto precisa"], "A maioria dos adultos precisa de 7 a 9 horas de sono por noite.")
add("saude", ["o que e uma vacina"], "Vacina é um preparado que estimula o sistema imunológico a criar defesas contra uma doença, sem causar a doença em si.")
add("saude", ["o que e pressao alta", "o que e hipertensao"], "Hipertensão, ou pressão alta, é quando a força do sangue contra as paredes das arterias fica constantemente acima do normal.")
add("saude", ["o que e diabetes"], "Diabetes é uma doença em que o corpo não produz insulina suficiente ou não a usa corretamente, elevando o nível de açúcar no sangue.")
add("saude", ["o que e colesterol"], "Colesterol é uma substância gordurosa presente no sangue, necessária ao corpo, mas que em excesso aumenta o risco de doenças cardíacas.")
add("saude", ["quais os beneficios de beber agua"], "Beber água regularmente ajuda na digestão, na regulação da temperatura do corpo e no funcionamento dos rins e do cérebro.")

# ---------------------------------------------------------------- ALIMENTACAO
add("alimentacao", ["quais os beneficios do cafe"], "O café, com moderação, pode aumentar o estado de alerta e a concentração, além de conter antioxidantes.")
add("alimentacao", ["o que e uma dieta balanceada"], "Dieta balanceada é aquela que inclui proporções adequadas de carboidratos, proteínas, gorduras, vitaminas e minerais.")
add("alimentacao", ["o que e proteina"], "Proteína é um nutriente essencial para a construção e reparação de tecidos do corpo, encontrado em carnes, ovos, leguminosas e outros alimentos.")
add("alimentacao", ["o que e carboidrato"], "Carboidrato é o principal nutriente responsável por fornecer energia rápida ao corpo, encontrado em pães, arroz e massas.")
add("alimentacao", ["quais alimentos tem mais vitamina c"], "Frutas cítricas como laranja, limão e acerola são conhecidas por serem ricas em vitamina C.")
add("alimentacao", ["o que e um alimento fermentado"], "Alimento fermentado é aquele transformado por microrganismos, como iogurte, queijo, pão e chucrute.")
add("alimentacao", ["de onde vem o chocolate"], "O chocolate é feito a partir das semente do cacau, uma planta originária da América Central e do Sul.")
add("alimentacao", ["de onde vem o cafe"], "O café tem origem na Etiópia, na África, e depois se espalhou pelo mundo, sendo hoje muito cultivado no Brasil.")
add("alimentacao", ["qual e o pais que mais produz cafe"], "O Brasil é o maior produtor de café do mundo.")
add("alimentacao", ["o que e a feijoada"], "Feijoada é um prato típico brasileiro feito com feijão preto e diversas carnes, servido tradicionalmente com arroz, couve e farofa.")
add("alimentacao", ["o que e churrasco"], "Churrasco é uma técnica de preparo de carnes grelhadas no fogo ou brasa, muito popular no Brasil, especialmente no Rio Grande do Sul.")
add("alimentacao", ["quais frutas sao originarias do brasil"], "Frutas como açaí, caju, maracujá, jabuticaba e pitanga são originárias do Brasil.")
add("alimentacao", ["o que e comida organica"], "Comida orgânica é aquela produzida sem uso de agrotóxicos ou fertilizantes sintéticos.")
add("alimentacao", ["quantos litros de agua uma pessoa deve beber por dia"], "A recomendação geral é de cerca de 2 a 2,5 litros de água por dia, podendo variar conforme o peso e a atividade física.")
add("alimentacao", ["o que e intolerancia a lactose"], "Intolerância à lactose é a dificuldade do corpo em digerir a lactose, o açúcar presente no leite, causando desconforto digestivo.")

# ---------------------------------------------------------------- ESPORTES
add("esportes", ["quantos jogadores tem um time de futebol"], "Um time de futebol tem 11 jogadores em campo, incluindo o goleiro.")
add("esportes", ["quantos jogadores tem um time de volei"], "Um time de vôlei tem 6 jogadores em quadra.")
add("esportes", ["quantos jogadores tem um time de basquete"], "Um time de basquete tem 5 jogadores em quadra.")
add("esportes", ["quantas copas do mundo o brasil ganhou"], "O Brasil ganhou 5 Copas do Mundo de futebol: em 1958, 1962, 1970, 1994 e 2002.")
add("esportes", ["quem foi pele"], "Pelé foi um dos maiores jogadores de futebol da história, tricampeão mundial pela seleção brasileira.")
add("esportes", ["a cada quantos anos acontece a copa do mundo"], "A Copa do Mundo de futebol acontece a cada 4 anos.")
add("esportes", ["a cada quantos anos acontecem os jogos olimpicos"], "Os Jogos Olímpicos de verão acontecem a cada 4 anos.")
add("esportes", ["onde foram as olimpiadas de 2016"], "As Olimpíadas de 2016 foram realizadas no Rio de Janeiro, no Brasil.")
add("esportes", ["o que e a formula 1"], "Fórmula 1 é a principal categoria de automobilismo do mundo, com carros monopostos de altíssima velocidade.")
add("esportes", ["quem foi ayrton senna"], "Ayrton Senna foi um piloto brasileiro tricampeão mundial de Fórmula 1, considerado um dos maiores da história do automobilismo.")
add("esportes", ["o que e o vôlei de praia"], "Vôlei de praia é uma modalidade do vôlei jogada na areia, geralmente em duplas.")
add("esportes", ["quantos sets tem um jogo de volei"], "Um jogo de vôlei é disputado em até 5 sets, sendo vencedor quem ganhar 3.")
add("esportes", ["o que e o mma"], "MMA, ou artes marciais mistas, é um esporte de combate que combina técnicas de luta como boxe, jiu-jitsu e muay thai.")
add("esportes", ["quem foi muhammad ali"], "Muhammad Ali foi um dos maiores boxeadores da história, conhecido por sua velocidade e por vencer o título mundial dos pesos pesados.")
add("esportes", ["o que e a maratona"], "Maratona é uma corrida de longa distância com 42,195 quilômetros, inspirada na corrida do soldado grego que anunciou a vitória em Maratona.")

# ---------------------------------------------------------------- MUSICA
add("musica", ["quantas notas musicais existem"], "Existem 7 notas musicais principais: dó, ré, mi, fá, sol, lá e si.")
add("musica", ["quem foi beethoven"], "Ludwig van Beethoven foi um compositor alemão, um dos mais importantes da história da música clássica, mesmo tendo perdido a audição.")
add("musica", ["quem foi mozart"], "Wolfgang Amadeus Mozart foi um compositor austríaco, considerado um dos maiores gênios da música clássica.")
add("musica", ["o que e samba"], "Samba é um gênero musical e de dança brasileiro, com raízes africanas, símbolo do carnaval e da cultura nacional.")
add("musica", ["o que e bossa nova"], "Bossa nova é um gênero musical brasileiro surgido no final dos anos 1950, misturando samba com influências do jazz.")
add("musica", ["quem foi tom jobim"], "Tom Jobim foi um compositor e músico brasileiro, um dos criadores da bossa nova, autor de clássicos como Garota de Ipanema.")
add("musica", ["o que e forro"], "Forró é um gênero musical e dança típicos do Nordeste do Brasil, tradicionalmente tocado com sanfona, zabumba e triângulo.")
add("musica", ["quantas cordas tem um violao"], "Um violão convencional tem 6 cordas.")
add("musica", ["quantas teclas tem um piano"], "Um piano padrão tem 88 teclas.")
add("musica", ["o que e o jazz"], "Jazz é um gênero musical que surgiu nos Estados Unidos no início do século 20, marcado pela improvisação e por raízes afro-americanas.")
add("musica", ["quem foram os beatles"], "Os Beatles foram uma banda britânica formada em Liverpool, uma das mais influentes da história da música pop e rock.")
add("musica", ["o que e o rock and roll"], "Rock and roll é um gênero musical surgido nos Estados Unidos nos anos 1950, combinando blues, country e rhythm and blues.")
add("musica", ["quem foi elvis presley"], "Elvis Presley foi um cantor americano conhecido como o Rei do Rock, um dos artistas mais influentes do século 20.")
add("musica", ["o que e mpb"], "MPB, ou Música Popular Brasileira, é um gênero que reúne diversos estilos brasileiros surgidos principalmente a partir dos anos 1960.")
add("musica", ["quem foi villa lobos"], "Heitor Villa-Lobos foi um dos maiores compositores brasileiros de música clássica, misturando influências eruditas e populares.")

# ---------------------------------------------------------------- ARTE E CULTURA
add("arte_cultura", ["quem pintou a mona lisa"], "A Mona Lisa foi pintada por Leonardo da Vinci, no início do século 16.")
add("arte_cultura", ["quem foi leonardo da vinci"], "Leonardo da Vinci foi um artista, inventor e cientista italiano do Renascimento, autor de obras como a Mona Lisa e a Última Ceia.")
add("arte_cultura", ["quem pintou a noite estrelada"], "A pintura A Noite Estrelada foi feita pelo artista holandês Vincent van Gogh, em 1889.")
add("arte_cultura", ["quem foi vincent van gogh"], "Vincent van Gogh foi um pintor holandês, um dos artistas mais influentes da história da arte, conhecido por obras como A Noite Estrelada e Girassóis.")
add("arte_cultura", ["quem foi pablo picasso"], "Pablo Picasso foi um pintor espanhol, cofundador do cubismo, um dos artistas mais importantes do século 20.")
add("arte_cultura", ["o que e o cubismo"], "Cubismo é um movimento artístico do início do século 20 que representa objetos e pessoas em formas geométricas fragmentadas.")
add("arte_cultura", ["o que e o renascimento"], "Renascimento foi um movimento cultural e artístico europeu, entre os séculos 14 e 16, marcado pelo resgate dos valores da Antiguidade Clássica.")
add("arte_cultura", ["quem foi tarsila do amaral"], "Tarsila do Amaral foi uma das principais pintoras do modernismo brasileiro, autora da obra Abaporu.")
add("arte_cultura", ["o que foi a semana de arte moderna"], "A Semana de Arte Moderna de 1922, em São Paulo, marcou o início do modernismo cultural no Brasil.")
add("arte_cultura", ["o que e o barroco"], "Barroco foi um estilo artístico surgido no século 17, marcado por dramaticidade, riqueza de detalhes e contrastes fortes.")
add("arte_cultura", ["o que e o carnaval"], "Carnaval é uma das principais festas populares do Brasil, marcada por desfiles de escolas de samba, blocos de rua e fantasias.")
add("arte_cultura", ["o que e uma escola de samba"], "Escola de samba é uma agremiação carnavalesca brasileira que desfila com samba-enredo, fantasias e carros alegóricos durante o carnaval.")
add("arte_cultura", ["o que e o folclore brasileiro"], "Folclore brasileiro é o conjunto de tradições, lendas, danças e costumes populares do Brasil, como a lenda do Saci e o boi-bumbá.")
add("arte_cultura", ["quem foi machado de assis"], "Machado de Assis é considerado um dos maiores escritores brasileiros, autor de obras como Dom Casmurro e Memórias Póstumas de Brás Cubas.")
add("arte_cultura", ["quem foi clarice lispector"], "Clarice Lispector foi uma escritora brasileira, uma das mais importantes da literatura em língua portuguesa do século 20.")

# ---------------------------------------------------------------- CINEMA E LITERATURA
add("cinema_literatura", ["quem escreveu romeu e julieta"], "Romeu e Julieta foi escrito por William Shakespeare, dramaturgo inglês do século 16.")
add("cinema_literatura", ["quem foi william shakespeare"], "William Shakespeare foi um escritor e dramaturgo inglês, considerado um dos maiores autores da literatura mundial.")
add("cinema_literatura", ["quem escreveu dom quixote"], "Dom Quixote foi escrito pelo espanhol Miguel de Cervantes, publicado no início do século 17.")
add("cinema_literatura", ["o que e um oscar"], "O Oscar é o principal prêmio da indústria cinematográfica, entregue anualmente pela Academia de Artes e Ciências Cinematográficas dos Estados Unidos.")
add("cinema_literatura", ["quem dirigiu o senhor dos aneis"], "A trilogia O Senhor dos Anéis foi dirigida por Peter Jackson, baseada nos livros de J.R.R. Tolkien.")
add("cinema_literatura", ["quem escreveu o senhor dos aneis"], "O Senhor dos Anéis foi escrito pelo autor britânico J.R.R. Tolkien.")
add("cinema_literatura", ["quem foi walt disney"], "Walt Disney foi um animador e empresário americano, fundador dos estúdios Disney e pioneiro da animação comercial.")
add("cinema_literatura", ["o que e a pixar"], "Pixar é um estúdio de animação americano, famoso por filmes como Toy Story, Procurando Nemo e Divertida Mente.")
add("cinema_literatura", ["quem dirigiu jurassic park"], "Jurassic Park foi dirigido por Steven Spielberg, lançado em 1993.")
add("cinema_literatura", ["quem foi steven spielberg"], "Steven Spielberg é um cineasta americano, diretor de filmes como Jurassic Park, E.T. e A Lista de Schindler.")
add("cinema_literatura", ["o que e ficcao cientifica"], "Ficção científica é um gênero narrativo que explora avanços tecnológicos, viagens no espaço e futuros possíveis ou alternativos.")
add("cinema_literatura", ["quem escreveu 1984"], "1984 foi escrito pelo autor britânico George Orwell, publicado em 1949, uma crítica aos regimes totalitários.")
add("cinema_literatura", ["quem foi jorge amado"], "Jorge Amado foi um escritor brasileiro conhecido por romances como Gabriela, Cravo e Canela e Capitães da Areia.")
add("cinema_literatura", ["quem escreveu o pequeno principe"], "O Pequeno Príncipe foi escrito pelo francês Antoine de Saint-Exupéry, publicado em 1943.")
add("cinema_literatura", ["o que e a netflix"], "Netflix é um serviço de streaming de filmes e séries por assinatura, fundado nos Estados Unidos em 1997.")

# ---------------------------------------------------------------- TECNOLOGIA / INFORMATICA
add("informatica", ["o que e um algoritmo"], "Algoritmo é uma sequência de passos bem definidos para resolver um problema ou realizar uma tarefa.")
add("informatica", ["o que e hardware"], "Hardware é a parte física de um computador, como processador, memória, placa-mãe e periféricos.")
add("informatica", ["o que e software"], "Software é o conjunto de programas e instruções que fazem um computador funcionar, incluindo o sistema operacional e os aplicativos.")
add("informatica", ["o que e a internet"], "Internet é uma rede mundial de computadores interligados, que permite a troca de informações entre praticamente qualquer lugar do mundo.")
add("informatica", ["quem inventou a internet"], "A internet surgiu de um projeto militar americano chamado ARPANET, nos anos 1960, e evoluiu com contribuições de diversos pesquisadores ao longo das décadas.")
add("informatica", ["o que e um servidor"], "Servidor é um computador ou programa que fornece dados, arquivos ou serviços para outros computadores conectados a ele, chamados de clientes.")
add("informatica", ["o que e a nuvem", "o que e computacao em nuvem"], "Computação em nuvem é o uso de servidores remotos, acessados pela internet, para armazenar dados e executar programas sem depender do computador local.")
add("informatica", ["o que e um byte"], "Byte é a unidade básica de medida de informação em computação, formada por 8 bits.")
add("informatica", ["o que e criptografia"], "Criptografia é a técnica de transformar informações em um código, para que só quem tem a chave correta consiga lê-las.")
add("informatica", ["o que e um firewall"], "Firewall é um sistema de segurança que controla o tráfego de dados entre uma rede e a internet, bloqueando acessos não autorizados.")
add("informatica", ["o que e codigo aberto", "o que e open source"], "Código aberto, ou open source, é quando o código-fonte de um programa é disponibilizado publicamente para qualquer pessoa usar, estudar ou modificar.")
add("informatica", ["o que e um bug"], "Bug é um erro em um programa de computador que faz ele se comportar de forma inesperada ou incorreta.")
add("informatica", ["o que e realidade virtual"], "Realidade virtual é uma tecnologia que simula um ambiente digital imersivo, geralmente por meio de óculos especiais.")
add("informatica", ["o que e realidade aumentada"], "Realidade aumentada é uma tecnologia que sobrepõe elementos digitais ao mundo real, geralmente vistos pela câmera de um celular ou óculos especiais.")
add("informatica", ["o que e a internet das coisas", "o que e iot"], "Internet das Coisas, ou IoT, é a conexão de objetos do dia a dia à internet, permitindo que eles coletem e troquem dados, como sensores e eletrodomésticos inteligentes.")

# ---------------------------------------------------------------- ECONOMIA
add("economia", ["o que e inflacao"], "Inflação é o aumento generalizado e contínuo dos preços de bens e serviços em uma economia, reduzindo o poder de compra da moeda.")
add("economia", ["o que e pib"], "PIB, ou Produto Interno Bruto, é a soma de todos os bens e serviços produzidos por um país em determinado período, usada para medir o tamanho de uma economia.")
add("economia", ["o que e taxa de juros"], "Taxa de juros é o percentual cobrado ou pago pelo uso do dinheiro em um empréstimo, financiamento ou investimento.")
add("economia", ["o que e a selic"], "Selic é a taxa básica de juros da economia brasileira, definida pelo Banco Central, usada como referência para todas as outras taxas de juros do país.")
add("economia", ["o que e uma acao na bolsa de valores"], "Ação é uma pequena parte do capital de uma empresa; quem a compra se torna sócio e pode ganhar com a valorização ou os dividendos.")
add("economia", ["o que e a bolsa de valores"], "Bolsa de valores é o ambiente onde ações e outros ativos financeiros de empresas são comprados e vendidos.")
add("economia", ["o que e o dolar"], "Dólar é a moeda oficial dos Estados Unidos, também usada como principal referência de comércio internacional no mundo.")
add("economia", ["o que e criptomoeda"], "Criptomoeda é uma moeda digital que usa criptografia e geralmente uma tecnologia chamada blockchain para funcionar sem depender de um banco central.")
add("economia", ["o que e o bitcoin"], "Bitcoin foi a primeira e é a mais conhecida criptomoeda do mundo, criada em 2009 por um autor com o pseudônimo Satoshi Nakamoto.")
add("economia", ["o que e oferta e demanda"], "Oferta e demanda é o princípio econômico básico que explica como o preço de um produto varia conforme a quantidade disponível e o interesse dos compradores.")
add("economia", ["o que e o pib per capita"], "PIB per capita é o valor do PIB de um país dividido pelo número de habitantes, usado para estimar a riqueza média por pessoa.")
add("economia", ["o que e recessao economica"], "Recessão é um período de queda na atividade econômica de um país, geralmente marcado por dois trimestres seguidos de queda no PIB.")
add("economia", ["o que e um monopolio"], "Monopólio é quando uma única empresa domina totalmente um mercado, sem concorrência relevante.")
add("economia", ["o que e importacao e exportacao"], "Importação é a compra de produtos de outros países, e exportação é a venda de produtos nacionais para o exterior.")
add("economia", ["o que e o imposto de renda"], "Imposto de renda é o tributo cobrado sobre os rendimentos de pessoas e empresas, usado pelo governo para financiar serviços públicos.")

# ---------------------------------------------------------------- NATUREZA / MEIO AMBIENTE
add("natureza", ["o que e o efeito estufa"], "Efeito estufa é o processo natural em que gases da atmosfera retêm calor do Sol, mantendo a Terra aquecida; quando intensificado pela poluição, causa o aquecimento global.")
add("natureza", ["o que e o aquecimento global"], "Aquecimento global é o aumento da temperatura média do planeta, causado principalmente pelo excesso de gases do efeito estufa lançados pela atividade humana.")
add("natureza", ["o que e reciclagem"], "Reciclagem é o processo de transformar materiais usados, como plástico, papel e vidro, em novos produtos, reduzindo o desperdício e a extração de recursos naturais.")
add("natureza", ["o que e energia renovavel"], "Energia renovável é aquela obtida de fontes naturais que se renovam, como sol, vento, água e biomassa.")
add("natureza", ["o que e energia solar"], "Energia solar é a energia elétrica gerada a partir da luz do sol, captada por painéis fotovoltaicos.")
add("natureza", ["o que e energia eolica"], "Energia eólica é a energia elétrica gerada a partir do vento, captada por turbinas eólicas.")
add("natureza", ["o que e o desmatamento"], "Desmatamento é a destruição ou remoção da vegetação natural de uma área, geralmente para agropecuária, mineração ou expansão urbana.")
add("natureza", ["qual e a maior bacia hidrografica do mundo"], "A Bacia Amazônica é a maior bacia hidrográfica do mundo.")
add("natureza", ["o que e biodiversidade"], "Biodiversidade é a variedade de formas de vida existentes em um ecossistema, incluindo plantas, animais, fungos e microrganismos.")
add("natureza", ["o que e um ecossistema"], "Ecossistema é o conjunto formado por seres vivos e o ambiente físico onde eles interagem entre si.")
add("natureza", ["o que sao os biomas brasileiros"], "Os principais biomas brasileiros são Amazônia, Cerrado, Caatinga, Mata Atlântica, Pampa e Pantanal.")
add("natureza", ["o que e o pantanal"], "O Pantanal é a maior planície alagável do mundo, localizada principalmente em Mato Grosso e Mato Grosso do Sul, no Brasil.")
add("natureza", ["o que e a camada de ozonio"], "A camada de ozônio é uma região da atmosfera que filtra boa parte da radiação ultravioleta do Sol, protegendo a vida na Terra.")
add("natureza", ["o que causa as chuvas acidas"], "Chuva ácida é causada pela poluição do ar, principalmente por gases de enxofre e nitrogênio liberados por indústrias e veículos.")
add("natureza", ["o que e o ciclo da agua"], "Ciclo da água é o processo contínuo de evaporação, condensação e precipitação da água entre a superfície da Terra e a atmosfera.")

# ---------------------------------------------------------------- CURIOSIDADES GERAIS
add("curiosidades", ["qual e o pais mais populoso do mundo"], "A Índia é atualmente o país mais populoso do mundo, superando a China.")
add("curiosidades", ["qual e a lingua mais falada do mundo"], "Considerando falantes nativos, o mandarim é a língua mais falada do mundo; contando todos os falantes, o inglês tem o maior alcance global.")
add("curiosidades", ["quantos idiomas existem no mundo"], "Estima-se que existam entre 6 e 7 mil idiomas falados no mundo atualmente.")
add("curiosidades", ["qual e a moeda oficial do brasil"], "A moeda oficial do Brasil é o Real.")
add("curiosidades", ["quantos fusos horarios tem o brasil"], "O Brasil tem 4 fusos horários oficiais.")
add("curiosidades", ["qual e a cidade mais populosa do brasil"], "São Paulo é a cidade mais populosa do Brasil.")
add("curiosidades", ["qual e o maior estado do brasil"], "O Amazonas é o maior estado do Brasil em extensão territorial.")
add("curiosidades", ["quantas letras tem o alfabeto"], "O alfabeto usado no português tem 26 letras.")
add("curiosidades", ["qual e o oceano que fica entre a america e a europa"], "O Oceano Atlântico fica entre as Américas e a Europa/África.")
add("curiosidades", ["qual e a torre mais alta do mundo"], "O Burj Khalifa, em Dubai, é o edifício mais alto do mundo, com mais de 828 metros.")
add("curiosidades", ["qual e a maior muralha do mundo"], "A Grande Muralha da China é considerada a maior estrutura construída pelo homem, com milhares de quilômetros de extensão.")
add("curiosidades", ["quantos fusos horarios existem no mundo"], "Existem cerca de 24 fusos horários principais no mundo, um para cada hora do dia.")
add("curiosidades", ["qual e o rio mais longo do mundo"], "O Rio Nilo e o Rio Amazonas disputam o título de rio mais longo do mundo, dependendo do critério de medição usado.")
add("curiosidades", ["qual e o pais com mais fuso horario"], "A Rússia é o país com o maior número de fusos horários, com 11 no total.")
add("curiosidades", ["quantos paises fazem fronteira com o brasil"], "O Brasil faz fronteira com 10 países da América do Sul.")
add("curiosidades", ["qual e a menor moeda do mundo"], "Não existe uma resposta única e universal, mas moedas de países com economias pequenas costumam ter o menor valor de câmbio em relação ao dólar.")
add("curiosidades", ["quantos hemisferios tem a terra"], "A Terra é dividida em 2 hemisférios: norte e sul (além da divisão leste-oeste pelos meridianos).")
add("curiosidades", ["qual e a linha que divide o hemisferio norte e sul"], "A linha do Equador é a linha imaginária que divide a Terra entre hemisfério norte e hemisfério sul.")
add("curiosidades", ["o que e o meridiano de greenwich"], "O Meridiano de Greenwich é a linha de referência usada para calcular as longitudes e os fusos horários do mundo.")
add("curiosidades", ["qual e a bandeira mais antiga do mundo ainda em uso"], "A bandeira da Dinamarca é considerada uma das mais antigas do mundo ainda em uso oficial.")

# ---------------------------------------------------------------- LOTE 4 (complemento)
add("curiosidades", ["quantos planetas tem anel no sistema solar"], "Quatro planetas do sistema solar têm anéis: Júpiter, Saturno, Urano e Netuno, sendo os de Saturno os mais visíveis.")
add("curiosidades", ["qual e o metal mais caro do mundo"], "O ródio é um dos metais mais caros do mundo, usado principalmente em catalisadores automotivos.")
add("curiosidades", ["qual e o metal mais leve do mundo"], "O lítio é o metal mais leve que existe naturalmente.")
add("curiosidades", ["qual e o material mais duro do mundo"], "O diamante é considerado o material natural mais duro do mundo.")
add("curiosidades", ["qual e o elemento quimico mais abundante no universo"], "O hidrogênio é o elemento químico mais abundante no universo.")
add("curiosidades", ["qual e o elemento quimico mais abundante na terra"], "O oxigênio é o elemento mais abundante na crosta terrestre.")
add("curiosidades", ["quantos musculos usamos para sorrir"], "Sorrir usa em média entre 10 e 12 músculos do rosto, dependendo da intensidade do sorriso.")
add("curiosidades", ["qual e a temperatura media do sol"], "A superfície do Sol tem uma temperatura de aproximadamente 5.500 graus Celsius; o núcleo chega a cerca de 15 milhões de graus.")
add("curiosidades", ["quanto tempo a luz do sol leva para chegar na terra"], "A luz do Sol leva cerca de 8 minutos e 20 segundos para chegar até a Terra.")
add("curiosidades", ["qual e o pais com mais ilhas do mundo"], "A Suécia é frequentemente citada como o país com mais ilhas do mundo, com mais de 200 mil.")
add("informatica", ["o que e um pixel"], "Pixel é a menor unidade de uma imagem digital, um pequeno ponto de cor que, junto com outros, forma a imagem na tela.")
add("informatica", ["o que e resolucao de tela"], "Resolução de tela é a quantidade de pixels exibidos, na largura e na altura, em uma tela; quanto maior, mais nítida a imagem.")
add("informatica", ["o que e um sistema operacional"], "Sistema operacional é o software principal que gerencia os recursos de um computador e permite a execução de outros programas, como Windows, Linux e macOS.")
add("informatica", ["o que e uma api"], "API é uma interface que permite que diferentes programas de software se comuniquem entre si, trocando dados e funcionalidades.")
add("informatica", ["o que e um banco de dados"], "Banco de dados é um sistema organizado para armazenar, consultar e gerenciar grandes quantidades de informação.")
add("esportes", ["quantas medalhas de ouro o brasil tem em olimpiadas", "quantas medalhas o brasil tem em olimpiadas"], "O Brasil já conquistou mais de 150 medalhas olímpicas ao longo da sua história, entre ouro, prata e bronze.")
add("esportes", ["o que e o handebol"], "Handebol é um esporte coletivo jogado com as mãos, em que duas equipes de 7 jogadores tentam marcar gols em uma quadra.")
add("esportes", ["o que e o rugby"], "Rugby é um esporte coletivo de contato físico intenso, jogado com uma bola oval, em que o objetivo é levar a bola até a linha de gol adversária.")
add("esportes", ["o que e o skate olimpico", "skate e esporte olimpico"], "O skate street e o skate park se tornaram modalidades olímpicas oficiais a partir dos Jogos de Tóquio 2020.")
add("musica", ["o que e um acorde"], "Acorde é a combinação de três ou mais notas musicais tocadas ao mesmo tempo.")
add("musica", ["quantas cordas tem um baixo eletrico"], "Um baixo elétrico convencional tem 4 cordas, embora existam modelos com 5 ou 6.")
add("animais", ["quanto tempo vive uma abelha"], "A abelha operária vive em média algumas semanas no verão, podendo viver alguns meses no inverno.")
add("animais", ["quantos anos vive um elefante"], "Elefantes podem viver entre 60 e 70 anos na natureza.")
add("saude", ["o que e uma alergia"], "Alergia é uma reação exagerada do sistema imunológico a uma substância normalmente inofensiva, como pólen, poeira ou certos alimentos.")
add("saude", ["o que e o sistema imunologico"], "Sistema imunológico é o conjunto de células e órgãos que defende o corpo contra vírus, bactérias e outros agentes invasores.")
add("natureza", ["o que e a fotossintese"], "Fotossíntese é o processo pelo qual as plantas usam luz solar, água e dióxido de carbono para produzir energia e liberar oxigênio.")

def main():
    with open(CAMINHO, "r", encoding="utf-8") as f:
        atuais = json.load(f)

    existentes = set()
    for item in atuais:
        for p in item.get("perguntas", []):
            existentes.add(p)

    adicionadas = 0
    for item in NOVAS:
        if any(p in existentes for p in item["perguntas"]):
            continue
        atuais.append(item)
        adicionadas += 1

    with open(CAMINHO, "w", encoding="utf-8") as f:
        json.dump(atuais, f, ensure_ascii=False, indent=2)

    print(f"Catalogo agora tem {len(atuais)} entradas ({adicionadas} novas adicionadas).")

if __name__ == "__main__":
    main()
